version: '2.1'
services:
  rbd-proxy:
    image: rainbond/rbd-proxy:tcp
    container_name: rbd-proxy
    volumes:
      - /tmp/nginx/sites_stream:/usr/local/nginx/conf/sites_stream
      - /tmp/nginx/sites_http:/usr/local/nginx/conf/sites_http
      - /tmp/nginx/ssl:/usr/local/nginx/conf/ssl
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    network_mode: "host"
    restart: always